name: Build Official Moto Kernel (Android 15)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Workflow
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev clang lld llvm git wget

      - name: Clone Official Motorola Kernel
        run: |
          # Прямое клонирование без лишних папок
          rm -rf kernel-msm
          git clone https://github.com/MotorolaMobilityLLC/kernel-msm

      - name: Install KernelSU
        run: |
          cd kernel-msm
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Download AOSP Clang
        run: |
          mkdir -p clang
          cd clang
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r487747c.tar.gz
          tar -xf clang-r487747c.tar.gz

      - name: Build Kernel
        run: |
          export PATH=$(pwd)/clang/bin:$PATH
          cd kernel-msm
          
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_COMPAT=arm-linux-gnueabi-
          
          # Твой конфиг для Moto G84
          make O=out vendor/bangkk_defconfig
          
          # Компиляция
          make -j$(nproc --all) O=out \
                      CC=clang \
                      CLANG_TRIPLE=aarch64-linux-gnu- \
                      LD=ld.lld \
                      AR=llvm-ar \
                      NM=llvm-nm \
                      OBJCOPY=llvm-objcopy \
                      OBJDUMP=llvm-objdump \
                      STRIP=llvm-strip \
                      LLVM=1 \
                      LLVM_IAS=1

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: Official-Kernel-Android15
          path: kernel-msm/out/arch/arm64/boot/Image
