name: Build KernelSU for Moto G84
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y head checkinstall build-essential bc subversion ca-certificates curl w3m wget binutils-aarch64-linux-gnu libncurses5-dev libssl-dev flex bison
          sudo apt install -y clang-14 lld-14 llvm-14

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 -b MMI-V1TCS35H.88-16-1 https://github.com/MotorolaMobilityLLC/kernel-msm kernel
          
      - name: Setup KernelSU
        run: |
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Build Kernel
        run: |
          cd kernel
          # Используем системный Clang 14 и LLD
          export PATH=/usr/lib/llvm-14/bin:$PATH
          make ARCH=arm64 O=out CROSS_COMPILE=aarch64-linux-gnu- CC=clang-14 LD=ld.lld-14 NM=llvm-nm-14 OBJCOPY=llvm-objcopy-14 OBJDUMP=llvm-objdump-14 STRIP=llvm-strip-14 vendor/holi_defconfig
          make -j$(nproc --all) ARCH=arm64 O=out CROSS_COMPILE=aarch64-linux-gnu- CC=clang-14 LD=ld.lld-14 NM=llvm-nm-14 OBJCOPY=llvm-objcopy-14 OBJDUMP=llvm-objdump-14 STRIP=llvm-strip-14

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-boot
          path: kernel/out/arch/arm64/boot/Image*
