name: Build KernelSU for Moto G84
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Kernel
        uses: ak774/github-actions-android-kernel-builder@main
        with:
          kernel_source: https://github.com/MotorolaMobilityLLC/kernel-msm
          kernel_branch: MMI-V1TCS35H.88-16-1
          config: vendor/holi_defconfig
          arch: arm64
          toolchain_url: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r487747c.tar.gz
          ksu: true
          ksu_version: main
