name: Build LineageOS Kernel (Android 16)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev clang lld llvm git wget

      - name: Clone LineageOS Kernel
        run: |
          rm -rf kernel-source
          # Клонируем ветку для Android 15/16 (bangkk)
          git clone --depth=1 --single-branch -b lineage-22.1 https://github.com/LineageOS/android_kernel_motorola_sm6375.git kernel-source

      - name: Install KernelSU
        run: |
          cd kernel-source
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Setup Clang
        run: |
          mkdir -p clang
          # Качаем напрямую архив, чтобы не мучиться с git clone
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r487747c.tar.gz
          tar -xf clang-r487747c.tar.gz -C clang

      - name: Build Kernel
        run: |
          # Прописываем путь к скачанному Clang
          export PATH=$(pwd)/clang/bin:$PATH
          cd kernel-source
          
          export ARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          
          # 1. Генерируем конфиг (явно указываем LLVM, чтобы не искал GCC)
          make O=out vendor/bangkk_defconfig CC=clang LLVM=1 LLVM_IAS=1
          
          # 2. Сама сборка со всеми флагами LLVM
          make -j$(nproc --all) O=out \
                      CC=clang \
                      LD=ld.lld \
                      AR=llvm-ar \
                      NM=llvm-nm \
                      OBJCOPY=llvm-objcopy \
                      OBJDUMP=llvm-objdump \
                      STRIP=llvm-strip \
                      LLVM=1 \
                      LLVM_IAS=1 \
                      CROSS_COMPILE=aarch64-linux-gnu- \
                      CROSS_COMPILE_COMPAT=arm-linux-gnueabi-

      - name: Upload Image
        uses: actions/upload-artifact
