name: Build KernelSU for Moto G84
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev libncurses-dev curl git

      - name: Download Toolchain
        run: |
          mkdir clang
          # Скачиваем официальный стабильный Toolchain от Google (AOSP)
          curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main-kernel-build-2024/clang-r497332.tar.gz
          tar -C clang -xzf clang-r497332.tar.gz

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 -b MMI-V1TCS35H.88-16-1 https://github.com/MotorolaMobilityLLC/kernel-msm kernel
          
      - name: Setup KernelSU
        run: |
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Build Kernel
        run: |
          cd kernel
          # Добавляем наш скачанный Clang в путь
          export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
          # Запускаем сборку с использованием только нашего Clang
          make ARCH=arm64 O=out CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1 vendor/holi_defconfig
          make -j$(nproc --all) ARCH=arm64 O=out CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-boot
          path: kernel/out/arch/arm64/boot/Image*
