name: Build KernelSU for Moto G84 (Kernel 5.4)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc build-essential flex bison libssl-dev libelf-dev libncurses-dev curl git clang-12 lld-12 llvm-12 binutils-aarch64-linux-gnu

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 -b MMI-V1TCS35H.88-16-1 https://github.com/MotorolaMobilityLLC/kernel-msm kernel
          
      - name: Setup KernelSU
        run: |
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Build Kernel
        run: |
          cd kernel
          export PATH=/usr/lib/llvm-12/bin:$PATH
          
          # Настройка конфига
          make ARCH=arm64 O=out CROSS_COMPILE=aarch64-linux-gnu- CC=clang-12 LD=ld.lld-12 NM=llvm-nm-12 OBJCOPY=llvm-objcopy-12 OBJDUMP=llvm-objdump-12 STRIP=llvm-strip-12 defconfig
          
          # Сборка с отключением варнингов, чтобы не падать на fs/built-in.a
          make -j$(nproc --all) ARCH=arm64 O=out CROSS_COMPILE=aarch64-linux-gnu- CC=clang-12 LD=ld.lld-12 NM=llvm-nm-12 OBJCOPY=llvm-objcopy-12 OBJDUMP=llvm-objdump-12 STRIP=llvm-strip-12 KCFLAGS="-w"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-Image
          path: kernel/out/arch/arm64/boot/Image
