name: Build KernelSU for Moto G84
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: coolsnowwolf/ubuntu-build-service:latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y bc build-essential flex bison libssl-dev libelf-dev libncurses-dev curl git python3

      - name: Download Clang
        run: |
          mkdir clang
          curl -L https://github.com/ZyCromerZ/Clang/releases/download/14.0.6-20220904-release/Clang-14.0.6-20220904.tar.gz -o clang.tar.gz
          tar -C clang -xzf clang.tar.gz

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 -b MMI-V1TCS35H.88-16-1 https://github.com/MotorolaMobilityLLC/kernel-msm kernel
          
      - name: Setup KernelSU
        run: |
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Build Kernel
        run: |
          cd kernel
          export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
          # Сборка через встроенный LLVM
          make ARCH=arm64 O=out CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1 vendor/holi_defconfig
          make -j$(nproc --all) ARCH=arm64 O=out CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-boot
          path: kernel/out/arch/arm64/boot/Image*
