name: Build KernelSU Moto G84
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc build-essential flex bison libssl-dev libelf-dev libncurses-dev curl git clang-14 lld-14 llvm-14 binutils-aarch64-linux-gnu

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 -b MMI-V1TCS35H.88-16-1 https://github.com/MotorolaMobilityLLC/kernel-msm kernel
          
      - name: Setup KernelSU
        run: |
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Build Kernel
        run: |
          cd kernel
          export PATH=/usr/lib/llvm-14/bin:$PATH
          
          # 1. Генерируем конфиг
          make ARCH=arm64 O=out CROSS_COMPILE=aarch64-linux-gnu- CC=clang-14 LD=ld.lld-14 NM=llvm-nm-14 OBJCOPY=llvm-objcopy-14 OBJDUMP=llvm-objdump-14 STRIP=llvm-strip-14 defconfig
          
          # 2. ИСПРАВЛЕНИЕ ОШИБОК ИЗ ТВОИХ СКРИНОВ
          sed -i 's/#elif/#else/g' kernel/taskstats.c
          
          # Фикс P_XO и P_GPLL0_OUT_AUX (скрин 2114)
          echo "#define P_GPLL0_OUT_AUX 0" >> include/dt-bindings/clock/qcom,gcc-qcs404.h
          echo "#define P_XO 0" >> include/dt-bindings/clock/qcom,gcc-qcs404.h
          
          # Фикс undefined symbol (скрин 3940 - линковка)
          # Принудительно включаем DRM и SCM в конфиг, чтобы они были доступны линковщику
          echo "CONFIG_DRM_PANEL=y" >> out/.config
          echo "CONFIG_QCOM_SCM=y" >> out/.config
          echo "CONFIG_XEN=n" >> out/.config

          # 3. СБОРКА
          make -j$(nproc --all) ARCH=arm64 O=out CROSS_COMPILE=aarch64-linux-gnu- \
            CC=clang-14 LD=ld.lld-14 NM=llvm-nm-14 OBJCOPY=llvm-objcopy-14 OBJDUMP=llvm-objdump-14 STRIP=llvm-strip-14 \
            KCFLAGS="-w -Wno-error -fno-builtin -fno-stack-protector -fno-integrated-as" \
            Image.gz

      - name: Upload Kernel Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: KernelSU-Image-G84
          path: kernel/out/arch/arm64/boot/Image.gz
