name: Build Moto G84 Kernel (Image.gz Only)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev clang lld llvm git wget libarchive-tools python3 python-is-python3

      - name: Clone Kernel Source
        run: |
          # Клонируем ветку Lineage 23.2 для твоего процессора
          git clone --depth=1 https://github.com/mikeNG/android_kernel_motorola_sm6375.git -b lineage-23.2 kernel-source

      - name: Setup KernelSU
        run: |
          cd kernel-source
          # Внедряем KernelSU
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Setup Clang (AOSP)
        run: |
          mkdir -p clang
          # Стабильный Clang для ядер 5.4
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r487747c.tar.gz
          tar -C clang/ -xzf clang-r487747c.tar.gz

      - name: Build Kernel
        run: |
          export PATH=$(pwd)/clang/bin:$PATH
          cd kernel-source
          
          export ARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_COMPAT=arm-linux-gnueabi-
          export CLANG_TRIPLE=aarch64-linux-gnu-
          
          mkdir -p out
          
          # 1. Генерируем конфиг
          make O=out vendor/holi-qgki_defconfig
          
          # 2. Включаем KSU и Kprobes
          ./scripts/config --file out/.config -e KSU
          ./scripts/config --file out/.config -e OVERLAY_FS
          ./scripts/config --file out/.config -e KPROBES
          ./scripts/config --file out/.config -e KPROBE_EVENTS
          
          make O=out olddefconfig

          # 3. Сборка только ядра
          make -j$(nproc --all) O=out \
                      CC=clang \
                      LD=ld.lld \
                      AR=llvm-ar \
                      NM=llvm-nm \
                      OBJCOPY=llvm-objcopy \
                      OBJDUMP=llvm-objdump \
                      STRIP=llvm-strip

      - name: Upload Kernel Only
        uses: actions/upload-artifact@v4
        with:
          name: Moto-G84-KSU-Kernel
          path: kernel-source/out/arch/arm64/boot/Image.gz
