name: Build LineageOS Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev clang lld llvm git wget libarchive-tools python3 python-is-python3

      - name: Clone Kernel Source
        run: |
          # Раз эта ссылка работает — не трогаем её!
          git clone --depth=1 https://github.com/LineageOS/android_kernel_motorola_sm6375 -b lineage-23.2 kernel-source

      - name: Setup KernelSU
        run: |
          cd kernel-source
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Setup Clang
        run: |
          # Клонируем весь репозиторий пребилтов
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 -b main clang
          # Проверим, что папка на месте (для логов)
          ls -d clang/clang-r*

      - name: Build Kernel
        run: |
          # Автоматически находим папку с r487747c (или аналогичной) и добавляем в PATH
          CLANG_DIR=$(ls -d $(pwd)/clang/clang-r*)
          export PATH="$CLANG_DIR/bin:$PATH"
          
          cd kernel-source
          
          export ARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_COMPAT=arm-linux-gnueabi-
          export CLANG_TRIPLE=aarch64-linux-gnu-
          
          mkdir -p out
          make O=out vendor/holi-qgki_defconfig
          
          ./scripts/config --file out/.config -e KSU -e OVERLAY_FS -e KPROBES -e KPROBE_EVENTS
          
          make O=out olddefconfig

          make -j$(nproc --all) O=out \
                      CC=clang \
                      LD=ld.lld \
                      AR=llvm-ar \
                      NM=llvm-nm \
                      OBJCOPY=llvm-objcopy \
                      OBJDUMP=llvm-objdump \
                      STRIP=llvm-strip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-KSU-Success
          path: kernel-source/out/arch/arm64/boot/Image.gz
